
swagger: '2.0'
info:
  version: "0.0.1"
  title: <img src=x onError=prompt(1)>
  description: <img src=x onError=prompt(1)>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
